#118 update resume show page, add accordian view to replace card view
ashToronto/career_crafter_pro pull request #120
Opened 2024-07-18 17:42 UTC by ashToronto

Updated resume show page to have an accordian view. This replaces the rendered cards and compliments the spacing taken up by the iframe: 

![Screenshot 2024-07-18 at 1 41 40 PM](https://github.com/user-attachments/assets/12767a92-a8fd-4185-b1a0-f01b8d72caa6)

We can further improve this layout in the future. it's meant to improve readability.

2024-07-19 16:37 UTC, SpicyNachos03 reviewed
I think the spinner for the PDF rendering works pretty well -

One thing of note I found in the accordion view was that depending on the order, the different elements (education, skills, etc) would be added to the accordion in different orders, compared to the standard order on the left hand side. I don't know if this is a big issue, but it seems a little inconsistent

2024-07-19 16:47 UTC, ykomarlu requested changes
Looks mostly good. The only thing is that the order of the dropdowns does not reflect the order of the sections in the resume.

Though this may prove problematic because each resume has its own unique ordering of sections.

Possible solution: maybe include the pencil edit icon right next to the sections present on the left side of the resume edit screen (no dropdowns needed). Or, have the dropdowns be in the same order as the sections in the left side of the resume edit screen.

2024-07-19 22:05 UTC, ashToronto commented
> I think the spinner for the PDF rendering works pretty well -
> 
> One thing of note I found in the accordion view was that depending on the order, the different elements (education, skills, etc) would be added to the accordion in different orders, compared to the standard order on the left hand side. I don't know if this is a big issue, but it seems a little inconsistent

this is easy enough to fix - i'll update - thanks for feedback

2024-07-19 22:09 UTC, ashToronto commented
> Looks mostly good. The only thing is that the order of the dropdowns does not reflect the order of the sections in the resume.
> 
> Though this may prove problematic because each resume has its own unique ordering of sections.
> 
> Possible solution: maybe include the pencil edit icon right next to the sections present on the left side of the resume edit screen (no dropdowns needed). Or, have the dropdowns be in the same order as the sections in the left side of the resume edit screen.

Yes there is reducdancy between the resume sidebar (creates a new section for work exp, education) and the accordian. 
The ultimate goal is to move each accordian section (they are all edit controller actions) into the same pages as the "create forms" i.e when you click on education sidebar it'll have the education edit accordian also - this way the user can both edit their existing sections and create a new one. 

I will create a new ticket for this and go over the logic with you during our next pairing/grooming session.

2024-07-20 13:18 UTC, ashToronto commented
I'm gonna go ahead and merge in cuz its will blocking my next ticket - the next ticket should address a lot of your pr comments :)

2024-07-20 13:19 UTC, merged